# Source oh-my-zsh if it is installed.
if [[ -d $HOME/.oh-my-zsh ]]; then
  # Path to your oh-my-zsh configuration.
  ZSH=$HOME/.oh-my-zsh

  # Set name of the theme to load.
  ZSH_THEME="blinks"

  # Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
  # Example format: plugins=(rails git textmate ruby lighthouse)
  plugins=(git ruby rails autojump)

  # Load default oh-my-zsh stuff
  source $ZSH/oh-my-zsh.sh
fi

# Don't change. The following determines where YADR is installed.
yadr=`find -L ~ -type file -maxdepth 2 -name .yadr | head | sed 's:\.yadr\/::'`

# Configuration
source $yadr/zsh/aliases
source $yadr/zsh/zsh_aliases

# Vim mode
bindkey -v

# Give me my bash style incremental search
bindkey '^R' history-incremental-search-backward

# Speed up git completion
# http://talkings.org/post/5236392664/zsh-and-slow-git-completion
__git_files () {
  _wanted files expl 'local files' _files
}

# Always pushd when changing directory
setopt auto_pushd

# Fuzzy matching of completions for when you mistype them:
zstyle ':completion:*' completer _complete _match _approximate
zstyle ':completion:*:match:*' original only
zstyle ':completion:*:approximate:*' max-errors 1 numeric

# Add path to our custom bins
export PATH=$yadr/bin:$yadr/bin/yadr:/Users/collin/.rbenv/shims:/Users/collin/.rbenv/bin:/usr/local/bin:/usr/local/sbin:/Users/collin/.rbenv/shims:/Users/collin/.rbenv/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin:/usr/local/share/python

chpwd() {
  if [ -f ".env" ]; then source .env; fi
}
